### ISSUE TITLE
Github actions for individual workspaces

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/heckarad.dev#5]
SPIKE on how to run Github actions for only the app or service when either changes within the monorepo setup.

**Comment by DHedgecock** [comment]
This is accomplished by providing paths to the `on` configuration like:

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "heckarad-application/**"
  push:
    branches:
      - master
    paths:
      - "heckarad-application/**"
```
